import type { Finding, RightsEntry } from "@/types";

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "f1",
    text: "Unblurred minor's face visible at playground scene. Requires parental consent documentation or face obscuring per COPPA/GDPR requirements.",
    severity: "CRITICAL",
    confidence: 96,
    timecode: 12.4,
    rule: "Minor Protection — COPPA/GDPR Art. 8",
    source: "gemini-2.5-flash",
    decision: "pending",
    remediation: "none",
  },
  {
    id: "f2",
    text: "Coca-Cola logo prominently displayed on desk for 4.2 seconds. Undisclosed product placement violates advertising standards.",
    severity: "MAJOR",
    confidence: 89,
    timecode: 34.1,
    rule: "Undisclosed Product Placement — ARPP Art. 9",
    source: "gemini-2.5-flash",
    decision: "pending",
    remediation: "none",
  },
  {
    id: "f3",
    text: "Background music detected — potential unlicensed track. Audio fingerprint matches 'Blinding Lights' by The Weeknd.",
    severity: "MAJOR",
    confidence: 82,
    timecode: 45.0,
    rule: "Unlicensed Music — Copyright Act Sec. 106",
    source: "twelve-labs-pegasus",
    decision: "pending",
    remediation: "none",
  },
  {
    id: "f4",
    text: "Mild expletive detected in dialogue. May violate pre-watershed broadcasting standards for content before 9pm.",
    severity: "MINOR",
    confidence: 74,
    timecode: 67.8,
    rule: "Language — OFCOM Broadcasting Code Sec. 1.14",
    source: "gemini-2.5-flash",
    decision: "pending",
    remediation: "none",
  },
  {
    id: "f5",
    text: "Vehicle license plate readable in street scene. Personal data exposure risk under GDPR right to privacy.",
    severity: "MINOR",
    confidence: 68,
    timecode: 89.2,
    rule: "PII Exposure — GDPR Art. 4(1)",
    source: "gemini-2.5-flash",
    decision: "pending",
    remediation: "none",
  },
  {
    id: "f6",
    text: "Simulated violence scene may exceed Roblox platform age-rating guidelines for content rated E10+.",
    severity: "CRITICAL",
    confidence: 91,
    timecode: 102.5,
    rule: "Age-Rating Violation — Roblox Community Standards",
    source: "twelve-labs-pegasus",
    decision: "pending",
    remediation: "none",
  },
];

export const MOCK_RIGHTS: RightsEntry[] = [
  {
    id: "r1",
    asset: "Blinding Lights — The Weeknd",
    type: "music",
    status: "pending",
    expiry_date: "2026-12-31",
    territory: "Worldwide",
    notes: "Sync license requested via Warner Music",
    source: "Manual",
    library: "Warner Chappell",
  },
  {
    id: "r2",
    asset: "Drone aerial B-roll — City skyline",
    type: "footage",
    status: "cleared",
    expiry_date: "2027-06-15",
    territory: "North America",
    notes: "Licensed from Shutterstock, editorial use",
    source: "Shutterstock",
    library: "Stock Footage",
  },
  {
    id: "r3",
    asset: "Talent Release — John Smith",
    type: "talent",
    status: "cleared",
    expiry_date: "2026-08-01",
    territory: "UK, US",
    notes: "Signed release on file",
    source: "Production",
    library: "Internal",
  },
  {
    id: "r4",
    asset: "Coca-Cola brand assets",
    type: "brand",
    status: "denied",
    expiry_date: "",
    territory: "N/A",
    notes: "Product placement not approved — must blur",
    source: "Brand team",
    library: "N/A",
  },
];
